mysql:
  type: mariadb
  hostname: localhost
  port: 3306
  database: my_database
  username: my_user
  password: my_password
  table: my_table
  driver: org.mariadb.jdbc.Driver
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048
  autoCommit: true
  connectionTimeout: 30000
  idleTimeout: 600000
  maxLifetime: 1800000
  minimumIdle: 10
  maximumPoolSize: 10

settings:
  start:
    world: world
    x: 0
    y: 100
    z: 0
  posOne:
    world: world
    x: -143
    y: 200
    z: 238
  posTwo:
    world: world
    x: -47
    y: 80
    z: 124
  spawn:
    world: world
    x: -66
    y: 63
    z: 143
  displayname: Parkour
  materials:
    - RED_CONCRETE
    - YELLOW_CONCRETE
    - GREEN_CONCRETE
    - LIME_CONCRETE
    - BLUE_CONCRETE
    - BLUE_CONCRETE
    - ORANGE_CONCRETE
    - LIGHT_BLUE_CONCRETE
